"""Tier 1: the rows the guide prints are rows the licensed workspace holds (NFR-11).

GUIDELINE, 2026-09-10, before the 0.15.0 release: the documentation must
carry usage examples in the matrix, real ones, and point a reader at files
they can take directly. Measured when it was asked, eight of the ten pieces
of 0.15.0 vocabulary appeared in the documentation ONLY as prose, with no
worked row anywhere: `MOTIONS`, `MOVING_BC_ALIAS`, `CLOCK_MOTION`,
`ROTATE`, `RAW`, the flight condition's `ADVANCE_RATIO`, `SYMMETRY_LOADS`
and `PERIODIC_COPIES`.

WHY THE ROWS ARE NOT WRITTEN IN THE PAGE. A row invented for a page is a row
nothing runs, and it rots the first time a cell changes meaning. The rows
the guide prints are rows of `tests/tier3_licensed/matriz_vocab.fs`, which
is rendered to a script on every commit and compared against a committed
golden, so the page quotes something the suite already executes. This module
is what ties the two together: a POL the page cites and the matrix does not
hold fails here.

The geometry those rows open is SYNTHETIC, generated by a committed
generator with its provenance recorded beside it, which is what lets the
whole workspace be committed and copied.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

from pyflightstream.cases.matrix import read_matrix

REPO = Path(__file__).resolve().parents[2]
GUIDE = REPO / "docs" / "workspace-and-workflows.md"
STARTED = REPO / "docs" / "getting-started.md"
VOCAB = REPO / "tests" / "tier3_licensed" / "matriz_vocab.fs"
GOLDENS = REPO / "tests" / "tier3_licensed" / "goldens" / "matriz_vocab"

#: Every POL the vocabulary matrix carries. A FLOOR, so deleting a row from
#: the matrix fails here rather than quietly shrinking what the guide can
#: point at.
VOCAB_ROWS_FLOOR = 5


def cited_pols(page: Path) -> set[str]:
    """Return the 8xxx POLs a page quotes, which are the vocabulary matrix's."""
    return set(re.findall(r"\b(8\d{3})\b", page.read_text(encoding="utf-8")))


def test_the_vocabulary_matrix_still_carries_the_rows_the_guide_points_at():
    """A row deleted from the workspace is an example a reader can no longer take."""
    rows = read_matrix(VOCAB, active_only=False)
    assert len(rows) >= VOCAB_ROWS_FLOOR, (
        f"matriz_vocab.fs carries {len(rows)} row(s) and the recorded floor is "
        f"{VOCAB_ROWS_FLOOR}. It is the workspace the documentation sends a reader to "
        "copy, so a row removed from it is an example a reader can no longer take."
    )


@pytest.mark.requirement("FR-61")
def test_every_row_the_guide_quotes_exists_in_the_matrix():
    """A page that quotes a POL quotes one the workspace holds.

    The guide prints these rows so a reader can copy the FILE rather than
    the page. A POL the page cites and the matrix does not hold sends that
    reader to a row that is not there, which is worse than printing nothing.
    """
    held = {row.pol for row in read_matrix(VOCAB, active_only=False)}
    cited = cited_pols(GUIDE) | cited_pols(STARTED)
    assert cited, (
        "no page quotes a row of the vocabulary matrix. The documentation is meant to "
        "point a reader at real rows they can take from tests/tier3_licensed/."
    )
    missing = sorted(cited - held)
    assert not missing, (
        f"the documentation quotes POL(s) {missing} that matriz_vocab.fs does not hold; "
        f"it holds {sorted(held)}"
    )


def test_every_quoted_row_has_a_rendered_golden():
    """The quoted row is one the suite renders, which is what stops it rotting.

    Quoting a row that parses but never builds would put an example in front
    of a reader that the suite has never executed. Each of these has at
    least one golden under `goldens/matriz_vocab/`, written by
    `python -m tests.tier3_licensed.offline` and compared on every commit.
    """
    assert GOLDENS.is_dir(), f"no goldens for the vocabulary matrix at {GOLDENS}"
    rendered = {
        stem.split("-", 1)[1].split("_", 1)[0] for stem in (p.stem for p in GOLDENS.glob("*.txt"))
    }
    cited = cited_pols(GUIDE) | cited_pols(STARTED)
    unrendered = sorted(cited - rendered)
    assert not unrendered, (
        f"the documentation quotes POL(s) {unrendered} with no rendered golden, so the "
        "example is not one the suite executes. Run "
        "`python -m tests.tier3_licensed.offline --write` and commit the result."
    )


def test_the_getting_started_walkthrough_names_each_kind_of_artifact():
    """A reader who has never seen this package meets all four files by name.

    The walkthrough exists because the concepts are the hard part rather
    than the syntax: which file answers which question, and why there are
    four of them rather than one.
    """
    text = STARTED.read_text(encoding="utf-8")
    for needed in (
        "inputs/references/r006.toml",
        "inputs/setups/s002.toml",
        "inputs/pproc/p005.toml",
        "41_TWIN.fsm",
        "matriz_vocab.fs",
    ):
        assert needed in text, f"the getting-started walkthrough no longer names {needed}"
