"""The recorded-exports extractor refuses a Total row that does not match its header.

`recorded_total_rows.csv` is the oracle every axes test is scored against, and it
is regenerated by `scripts/extract_recorded_total_rows.py` on the licensed
machine. The extractor zipped the header against the row leniently, so a row
printed short produced a narrower dict in silence (release review of 0.24.0,
QA-Q3). A trailing comma, which the solver prints, is not a cell.
"""

from __future__ import annotations

import importlib.util
from pathlib import Path

import pytest

SCRIPT = Path(__file__).parents[2] / "scripts" / "extract_recorded_total_rows.py"
HEADER = "Surface, CL, CDi, CDo, Cx, Cy, Cz,"


def _extractor():
    spec = importlib.util.spec_from_file_location("extract_recorded_total_rows", SCRIPT)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_a_row_as_long_as_its_header_reads_as_printed_trailing_comma_and_all():
    text = (
        f"{HEADER}\nTotal, +0.18828, +0.0012418, +0.0196424, +0.0274326, -0.0000032, +0.1871579,\n"
    )
    assert _extractor().total_row(text) == {
        "CL": "+0.18828",
        "CDi": "+0.0012418",
        "CDo": "+0.0196424",
        "Cx": "+0.0274326",
        "Cy": "-0.0000032",
        "Cz": "+0.1871579",
    }


def test_a_row_shorter_than_its_header_is_refused_naming_both_counts():
    text = f"{HEADER}\nTotal, +0.18828, +0.0012418, +0.0196424, +0.0274326,\n"
    with pytest.raises(ValueError) as refused:
        _extractor().total_row(text)
    assert "4 cells" in str(refused.value) and "header of 6" in str(refused.value)
