"""Tier 1, 0.32.0 package C: geometry generated by the solver's CCS commands.

A matrix row names a CCS file (Component Cross-Section, the vendor's parametric
geometry format) in its ``GEOMETRY`` cell, and the ``[import.ccs]`` table of the
file's sidecar says how the solver makes a mesh of it: a wing, a fuselage or a
body of revolution lofted from ONE component by the curve route that licensed
round 1 accepted on 26.124 (``CAD_CREATE_INITIALIZE``,
``CAD_CREATE_IMPORT_CURVE_CCS``, ``CAD_CREATE_CURVE_SELECT -1``, the loft), or
every component imported whole by ``CCS_IMPORT`` (the file route). A wing may
declare its control surfaces (CCS-2), and a row on the file route chooses the
direction of every ``Relaxed_TE`` shedding line with ``CCS_SHEDDING`` (G35).

The fixtures are synthetic shapes written from public shape laws: a symmetric
airfoil, a circular pod and an ellipse, never a research geometry.
"""

from __future__ import annotations

import math
import sys
from pathlib import Path

import pytest

from pyflightstream import cases
from pyflightstream.cases import CampaignConfigError
from pyflightstream.cases.workflows import build_script
from pyflightstream.script import CommandArgumentError, Script, helpers
from pyflightstream.workspace import InputArtifactError
from pyflightstream.workspace.inputs import read_mesh_import
from pyflightstream.workspace.matrix import resolve_matrix
from tests.tier1_offline.test_matrix_run import RECIPES, make_library, write_matrix

BUILD = "26.124"

#: One steady row naming a CCS file; ``{tail}`` appends row keys.
ROW = (
    "7001 | TestCcs | CCS | 3.10 | 0.0890 | AL | 0.0 | r003 | s002 | e001 "
    "| 003 | {build} |  0 | 1 | OUTPUTS: loads_{{point}}.txt / VELOCITY: 30.0 "
    "/ GEOMETRY: {geometry}{tail}"
)


def _fmt(value: float) -> str:
    return f"{value + 0.0:.6f}"


def _airfoil(chord: float = 1.0, n: int = 7) -> list[tuple[float, float]]:
    """A closed symmetric section, trailing edge upper, leading edge, trailing edge lower."""
    xs = [0.5 * (1.0 - math.cos(math.pi * i / (n - 1))) for i in range(n)]

    def half(x: float) -> float:
        return 0.6 * (0.2969 * math.sqrt(x) - 0.1260 * x - 0.3516 * x**2 + 0.2843 * x**3)

    upper = [(chord * x, chord * half(x)) for x in reversed(xs)]
    lower = [(chord * x, -chord * half(x)) for x in xs[1:]]
    return upper + lower


def _wing(name: str) -> list[str]:
    lines = [f"Component;{name}", "LiftingSurface;true"]
    for y in (0.0, 4.0):
        flat = [f"{_fmt(x)};{_fmt(y)};{_fmt(z)}" for x, z in _airfoil()]
        lines.append("CrossSection;" + ";".join(flat))
    return lines


def _fuselage(name: str, extra: tuple[str, ...] = ()) -> list[str]:
    lines = [f"Component;{name}", "LiftingSurface;false", *extra]
    for x in (0.1, 1.0, 2.0):
        radius = 0.5 * math.sin(math.pi * x / 2.1) ** 0.5
        points = [
            f"{_fmt(x)};{_fmt(radius * math.cos(t))};{_fmt(radius * math.sin(t))}"
            for t in (2.0 * math.pi * k / 8 for k in range(9))
        ]
        lines.append("CrossSection;" + ";".join(points))
    return lines


def _revolution(name: str) -> list[str]:
    profile = [
        f"{_fmt(x)};{_fmt(0.4 * math.sqrt(max(0.0, 1.0 - ((x - 1.5) / 1.5) ** 2)))};0.000000"
        for x in (3.0 * k / 6 for k in range(7))
    ]
    return [
        f"Component;{name}",
        "LiftingSurface;false",
        "RevolveBody;0.0;0.0;0.0;1.0;0.0;0.0;0.0;360.0",
        "CrossSection;" + ";".join(profile),
    ]


def ccs_file(*components: list[str]) -> str:
    body: list[str] = ["Aircraft;PYFS_TEST", "Units;Meter", ""]
    for component in components:
        body.extend(component)
        body.append("")
    return "\n".join(body)


#: One file, three components: 1 wing, 2 fuselage, 3 body of revolution.
THREE = ccs_file(_wing("CCS_WING"), _fuselage("CCS_FUS"), _revolution("CCS_REV"))


def _sidecar(boundaries: list[str], ccs: str, units: str = "METER") -> str:
    names = ", ".join(f'"{name}"' for name in boundaries)
    return f'boundaries = [{names}]\n\n[import]\nunits = "{units}"\n\n[import.ccs]\n{ccs}'


def _library(tmp_path, stem: str, text: str, sidecar: str, suffix: str = ".csv"):
    workspace = make_library(tmp_path, register_build=(BUILD, Path(sys.executable).as_posix()))
    geometries = workspace.inputs_dir / "geometries"
    (geometries / f"{stem}{suffix}").write_text(text, encoding="utf-8")
    (geometries / f"{stem}.boundaries.toml").write_text(sidecar, encoding="utf-8")
    return workspace


def _case(tmp_path, workspace, geometry: str, tail: str = ""):
    """Bind the one row through the plan's own binding and return its case at alpha 0."""
    matrix = write_matrix(
        tmp_path / "ccs.fs", [ROW.format(build=BUILD, geometry=geometry, tail=tail)]
    )
    resolved = resolve_matrix(matrix, workspace, name="matrix", fs_version=BUILD, recipes=RECIPES)
    case = resolved.campaign.sims[0]
    return case.model_copy(update={"point": {"alpha": 0.0}, "outputs": ["loads_a+00.0.txt"]})


def _built(case) -> tuple[Script, list[str]]:
    script = Script(BUILD)
    build_script(case, script)
    return script, script.render().splitlines()


def _row_case(tmp_path, stem: str, ccs: str, boundaries: list[str], **kwargs):
    text = kwargs.pop("text", THREE)
    units = kwargs.pop("units", "METER")
    tail = kwargs.pop("tail", "")
    workspace = _library(tmp_path, stem, text, _sidecar(boundaries, ccs, units))
    return _case(tmp_path, workspace, f"{stem}.csv", tail)


def _index(lines: list[str], line: str) -> int:
    assert line in lines, f"{line!r} is not in the script:\n" + "\n".join(lines[:60])
    return lines.index(line)


def _curve_route(lines: list[str], geometry: str, component: int) -> int:
    """Assert the curve prelude, in order, and return the index of the selection line."""
    initialize = _index(lines, "CAD_CREATE_INITIALIZE")
    imported = _index(lines, f"CAD_CREATE_IMPORT_CURVE_CCS METER 1 {component}")
    assert lines[imported + 1] == geometry
    selected = _index(lines, "CAD_CREATE_CURVE_SELECT -1")
    assert initialize < imported < selected
    return selected


# --- CCS-1: the wing, the fuselage and the body of revolution ---------------------------


def test_p0320_ccs1_wing_is_lofted_from_the_rows_ccs_file_by_the_curve_route(tmp_path):
    """P0320-CCS1-WING: the row's GEOMETRY and its sidecar make the wing, nothing else opens."""
    case = _row_case(tmp_path, "wing", 'kind = "wing"\ncomponent = 1\n', ["WING"])
    script, lines = _built(case)
    selected = _curve_route(lines, str(case.geometry), 1)
    loft = _index(lines, "CAD_CREATE_WING_MESH_FROM_CCS WING TRUE SHARP TRUE C2 C0")
    units = _index(lines, "SET_SIMULATION_LENGTH_UNITS METER")
    assert selected < loft < units
    assert not any(line.split(" ")[0] in {"OPEN", "IMPORT", "NEW_SIMULATION"} for line in lines)
    assert script.num_boundaries == 1
    assert script.entities.labels("boundaries") == {"WING": 1}


def test_p0320_ccs1_wing_states_its_loft_and_its_subdivisions_before_the_loft(tmp_path):
    """P0320-CCS1-WING: every wing key reaches its argument, the subdivisions before the loft."""
    ccs = (
        'kind = "wing"\ncomponent = 1\nmark_trailing_edges = false\n'
        'trailing_edge = "BLUNT"\nclose_ends = "CLOSED"\nloft_u = "C0"\nloft_v = "C2"\n'
        "subdivisions = { chord = 30, span = 12 }\n"
    )
    case = _row_case(tmp_path, "wing", ccs, ["WING"])
    _, lines = _built(case)
    selected = _curve_route(lines, str(case.geometry), 1)
    chord = _index(lines, "CCS_WING_MESH_SUBDIVISIONS CHORD 30")
    span = _index(lines, "CCS_WING_MESH_SUBDIVISIONS SPAN 12")
    loft = _index(lines, "CAD_CREATE_WING_MESH_FROM_CCS WING FALSE BLUNT CLOSED C0 C2")
    assert selected < chord < span < loft


def test_p0320_ccs1_fuselage_is_lofted_from_its_component(tmp_path):
    """P0320-CCS1-FUSELAGE: the second component, radial and axial lofts C2 by default."""
    case = _row_case(tmp_path, "fus", 'kind = "fuselage"\ncomponent = 2\n', ["FUS"])
    script, lines = _built(case)
    selected = _curve_route(lines, str(case.geometry), 2)
    loft = _index(lines, "CAD_CREATE_FUSELAGE_MESH_FROM_CCS FUS TRUE C2 C2")
    assert selected < loft < _index(lines, "SET_SIMULATION_LENGTH_UNITS METER")
    assert script.entities.labels("boundaries") == {"FUS": 1}


def test_p0320_ccs1_revolution_is_revolved_about_the_reference_axis_it_names(tmp_path):
    """P0320-CCS1-REVOLUTION: the third component, revolved in the reference frame."""
    ccs = 'kind = "revolution"\ncomponent = 3\naxis = "X"\nend_angle_deg = 180.0\n'
    case = _row_case(tmp_path, "rev", ccs, ["REV"])
    script, lines = _built(case)
    selected = _curve_route(lines, str(case.geometry), 3)
    loft = _index(lines, "CAD_CREATE_REVOLVE_MESH_FROM_CCS REV 1 X 0.0 180.0 TRUE C2 C2")
    assert selected < loft
    assert script.entities.labels("boundaries") == {"REV": 1}


def test_p0320_ccs1_revolution_default_is_a_full_turn(tmp_path):
    """P0320-CCS1-REVOLUTION: with no angles stated the body is 0 to 360 degrees about X."""
    case = _row_case(tmp_path, "rev", 'kind = "revolution"\ncomponent = 3\n', ["REV"])
    _, lines = _built(case)
    _index(lines, "CAD_CREATE_REVOLVE_MESH_FROM_CCS REV 1 X 0.0 360.0 TRUE C2 C2")


def test_p0320_ccs1_the_three_emitters_are_the_route_each_kind_takes(tmp_path):
    """P0320-CCS1-WING, -FUSELAGE, -REVOLUTION: each public emitter refuses another kind."""
    from pyflightstream.cases.ccs_fuselage import emit_ccs_fuselage
    from pyflightstream.cases.ccs_revolution import emit_ccs_revolution
    from pyflightstream.cases.ccs_wing import emit_ccs_wing

    case = _row_case(tmp_path, "wing", 'kind = "wing"\ncomponent = 1\n', ["WING"])
    for emitter in (emit_ccs_fuselage, emit_ccs_revolution):
        with pytest.raises(CampaignConfigError, match="wing"):
            emitter(Script(BUILD), case)
    script = Script(BUILD)
    emit_ccs_wing(script, case)
    assert "CAD_CREATE_WING_MESH_FROM_CCS WING TRUE SHARP TRUE C2 C0" in script.render()


@pytest.mark.parametrize(
    ("ccs", "boundaries", "needles"),
    [
        ('kind = "wing"\ncomponent = 4\n', ["WING"], ("component 4", "3 component")),
        ('kind = "fuselage"\ncomponent = 2\n', ["A", "B"], ("one boundary",)),
        ('kind = "wing"\ncomponent = 1\n', ["MY WING"], ("whitespace",)),
    ],
    ids=["component-beyond-the-file", "two-names", "spaced-name"],
)
def test_p0320_ccs1_a_loft_that_cannot_be_made_is_refused_before_any_seat(
    tmp_path, ccs, boundaries, needles
):
    """P0320-CCS1-WING: a loft whose component or name cannot hold is refused naming it."""
    case = _row_case(tmp_path, "wing", ccs, boundaries)
    with pytest.raises(CampaignConfigError) as refusal:
        _built(case)
    for needle in needles:
        assert needle in str(refusal.value)


def test_p0320_ccs1_a_loft_refuses_the_file_unit(tmp_path):
    """P0320-CCS1-FUSELAGE: the curve route states a unit; FILE belongs to the file route."""
    case = _row_case(tmp_path, "fus", 'kind = "fuselage"\ncomponent = 2\n', ["FUS"], units="FILE")
    with pytest.raises(CampaignConfigError, match="FILE"):
        _built(case)


def test_p0320_ccs1_a_loft_refuses_the_unit_that_names_no_length(tmp_path):
    """P0320-CCS1-WING: OTHER names no length, refused on a loft as on a raw mesh import.

    ``CAD_CREATE_IMPORT_CURVE_CCS`` lists OTHER among its units, and a curve
    read in it would be scaled by whatever the solver assumes, which is the
    assumed unit the ``[import]`` table exists to rule out.
    """
    case = _row_case(tmp_path, "wing", 'kind = "wing"\ncomponent = 1\n', ["WING"], units="OTHER")
    with pytest.raises(CampaignConfigError, match="OTHER"):
        _built(case)


@pytest.mark.parametrize(
    ("ccs", "key"),
    [
        ('kind = "fuselage"\ncomponent = 2\ntrailing_edge = "SHARP"\n', "trailing_edge"),
        ('kind = "revolution"\ncomponent = 3\nsubdivisions = { chord = 3 }\n', "subdivisions"),
        ('kind = "wing"\ncomponent = 1\naxis = "Y"\n', "axis"),
        ('kind = "file"\ncomponent = 1\n', "component"),
        ('kind = "wing"\ncomponent = 1\nsweep = 3\n', "sweep"),
        ('kind = "wing"\n', "component"),
    ],
)
def test_p0320_ccs1_a_key_the_kind_does_not_read_is_refused_at_binding(tmp_path, ccs, key):
    """P0320-CCS1-REVOLUTION: a key written under the wrong kind is refused, never ignored."""
    workspace = _library(tmp_path, "shape", THREE, _sidecar(["X"], ccs))
    with pytest.raises(InputArtifactError) as refusal:
        _case(tmp_path, workspace, "shape.csv")
    assert key in str(refusal.value)


def test_p0320_ccs1_ccs_options_beside_a_raw_mesh_are_refused(tmp_path):
    """P0320-CCS1-WING: an ``[import.ccs]`` table beside a mesh that is not a CCS file."""
    from pyflightstream.cases.workflows import _open_geometry
    from tests.tier1_offline.test_workflows import steady_case

    mesh = tmp_path / "wing.stl"
    mesh.write_text("solid w\nendsolid w\n", encoding="utf-8")
    spec = cases.MeshImport(units="METER", ccs={"kind": "wing", "component": 1})
    case = steady_case().model_copy(
        update={"geometry": str(mesh), "mesh_import": spec, "inventory": ("Wing",)}
    )
    with pytest.raises(CampaignConfigError, match="CCS"):
        _open_geometry(case, Script(BUILD))


def test_p0320_ccs1_a_ccs_file_without_its_table_is_refused(tmp_path):
    """P0320-CCS1-WING: a CCS file with no ``[import.ccs]`` names how to write one."""
    workspace = _library(tmp_path, "wing", THREE, 'boundaries = ["WING"]\n')
    case = _case(tmp_path, workspace, "wing.csv")
    with pytest.raises(CampaignConfigError, match=r"import\.ccs"):
        _built(case)


def test_p0320_ccs1_a_loft_refuses_the_raw_mesh_boundary_condition_tables(tmp_path):
    """P0320-CCS1-WING: the loft marks its own trailing edge; a table would mark it twice."""
    sidecar = _sidecar(["WING"], 'kind = "wing"\ncomponent = 1\n') + (
        '\n[trailing_edges]\ndetect = "auto"\n'
    )
    workspace = _library(tmp_path, "wing", THREE, sidecar)
    case = _case(tmp_path, workspace, "wing.csv")
    with pytest.raises(CampaignConfigError, match="trailing_edges"):
        _built(case)


# --- CCS-2: the control surface of a CCS wing -------------------------------------------

AILERON = (
    '[[import.ccs.control_surfaces]]\nname = "AIL"\nv0 = 0.5\nv1 = 0.9\nu0 = 0.25\n'
    "u1 = 0.25\nhinge_height = 0.5\nangle_deg = 20.0\nslot_gap_pct = 1.0\n"
)


def test_p0320_ccs2_control_surface_is_declared_with_all_ten_arguments_before_the_loft(
    tmp_path,
):
    """P0320-CCS2-CONTROL-SURFACE: the ten-token form, SPACE and AXIS always written.

    Round 1 on 26.124 refused the eight-token line the manual's own sample prints
    (``Review command syntax and arguments``); SRC-752 p.303 declares ten
    parameters, so the route writes SPACE and AXIS on every declaration.
    """
    ccs = 'kind = "wing"\ncomponent = 1\n' + AILERON
    case = _row_case(tmp_path, "wing", ccs, ["WING"])
    _, lines = _built(case)
    selected = _curve_route(lines, str(case.geometry), 1)
    surface = _index(
        lines, "NEW_CCS_WING_CONTROL_SURFACE AIL 0.5 0.9 0.25 0.25 0.5 20.0 1.0 PARAMETRIC Y"
    )
    loft = _index(lines, "CAD_CREATE_WING_MESH_FROM_CCS WING TRUE SHARP TRUE C2 C0")
    assert selected < surface < loft


def test_p0320_ccs2_control_surface_in_real_space_names_its_axis(tmp_path):
    """P0320-CCS2-CONTROL-SURFACE: REAL spanwise limits along a reference axis."""
    real = AILERON.replace("v0 = 0.5\nv1 = 0.9\n", "v0 = 2.0\nv1 = 3.6\n") + (
        'space = "REAL"\naxis = "Y"\n'
    )
    case = _row_case(tmp_path, "wing", 'kind = "wing"\ncomponent = 1\n' + real, ["WING"])
    _, lines = _built(case)
    _index(lines, "NEW_CCS_WING_CONTROL_SURFACE AIL 2.0 3.6 0.25 0.25 0.5 20.0 1.0 REAL Y")


def test_p0320_ccs2_control_surfaces_follow_the_subdivisions_in_the_order_written(tmp_path):
    """P0320-CCS2-CONTROL-SURFACE: selection, subdivisions, each surface as written, loft."""
    flap = AILERON.replace('name = "AIL"', 'name = "FLAP"').replace(
        "v0 = 0.5\nv1 = 0.9\n", "v0 = 0.1\nv1 = 0.4\n"
    )
    ccs = 'kind = "wing"\ncomponent = 1\nsubdivisions = { chord = 30 }\n' + flap + AILERON
    case = _row_case(tmp_path, "wing", ccs, ["WING"])
    _, lines = _built(case)
    selected = _curve_route(lines, str(case.geometry), 1)
    chord = _index(lines, "CCS_WING_MESH_SUBDIVISIONS CHORD 30")
    first = _index(
        lines, "NEW_CCS_WING_CONTROL_SURFACE FLAP 0.1 0.4 0.25 0.25 0.5 20.0 1.0 PARAMETRIC Y"
    )
    second = _index(
        lines, "NEW_CCS_WING_CONTROL_SURFACE AIL 0.5 0.9 0.25 0.25 0.5 20.0 1.0 PARAMETRIC Y"
    )
    loft = _index(lines, "CAD_CREATE_WING_MESH_FROM_CCS WING TRUE SHARP TRUE C2 C0")
    assert selected < chord < first < second < loft


@pytest.mark.parametrize("build", ["26.100", "26.101"])
def test_p0320_ccs2_a_build_with_the_eight_argument_grammar_refuses_the_line(tmp_path, build):
    """P0320-CCS2-CONTROL-SURFACE: refused at the emitter where SPACE and AXIS do not exist."""
    from pyflightstream.cases.ccs_wing import emit_ccs_wing

    case = _row_case(tmp_path, "wing", 'kind = "wing"\ncomponent = 1\n' + AILERON, ["WING"])
    with pytest.raises(CommandArgumentError, match="8 arguments"):
        emit_ccs_wing(Script(build), case)


@pytest.mark.parametrize(
    ("change", "needle"),
    [
        (("u0 = 0.25", "u0 = 0.5"), "u0"),
        (("v1 = 0.9", "v1 = 0.4"), "v1"),
        (("hinge_height = 0.5", "hinge_height = 1.5"), "hinge_height"),
        (("v1 = 0.9", "v1 = 1.2"), "v1"),
        (('name = "AIL"', 'name = "MY AIL"'), "name"),
    ],
)
def test_p0320_ccs2_a_control_surface_outside_the_manuals_ranges_is_refused(
    tmp_path, change, needle
):
    """P0320-CCS2-CONTROL-SURFACE: refused at binding, naming the field and its range."""
    surface = AILERON.replace(*change)
    workspace = _library(
        tmp_path, "wing", THREE, _sidecar(["WING"], 'kind = "wing"\ncomponent = 1\n' + surface)
    )
    with pytest.raises(InputArtifactError) as refusal:
        _case(tmp_path, workspace, "wing.csv")
    assert needle in str(refusal.value)


def test_p0320_ccs2_a_control_surface_on_a_fuselage_is_refused(tmp_path):
    """P0320-CCS2-CONTROL-SURFACE: only a wing carries one; refused, never dropped."""
    workspace = _library(
        tmp_path, "fus", THREE, _sidecar(["FUS"], 'kind = "fuselage"\ncomponent = 2\n' + AILERON)
    )
    with pytest.raises(InputArtifactError, match="control_surfaces"):
        _case(tmp_path, workspace, "fus.csv")


def test_p0320_ccs2_a_wing_with_control_surfaces_may_name_the_boundaries_they_add(tmp_path):
    """P0320-CCS2-CONTROL-SURFACE: the loft is the first name, the rest are declared after."""
    ccs = 'kind = "wing"\ncomponent = 1\n' + AILERON
    case = _row_case(tmp_path, "wing", ccs, ["WING", "AIL"])
    script, lines = _built(case)
    _index(lines, "CAD_CREATE_WING_MESH_FROM_CCS WING TRUE SHARP TRUE C2 C0")
    assert script.entities.labels("boundaries") == {"WING": 1, "AIL": 2}


# --- G35: the row chooses the direction of a Relaxed_TE shedding line --------------------

RELAXED_FUSELAGE = ccs_file(_fuselage("CCS_FUS", ("Relaxed_TE;0.5;0.2;0.8",)))
FILE_ROUTE = 'kind = "file"\n'


def _file_case(tmp_path, text=RELAXED_FUSELAGE, tail="", boundaries=("CCS_FUS",)):
    return _row_case(
        tmp_path, "g35", FILE_ROUTE, list(boundaries), text=text, units="FILE", tail=tail
    )


def _ccs_import_file(lines: list[str]) -> str:
    start = _index(lines, "CCS_IMPORT")
    assert lines[start + 1 : start + 4] == [
        "CLOSE_COMPONENT_ENDS DISABLE",
        "UPDATE_PROPERTIES DISABLE",
        "CLEAR_EXISTING ENABLE",
    ]
    assert lines[start + 4].startswith("FILE ")
    return lines[start + 4].removeprefix("FILE ")


def test_p0320_g35_the_file_route_imports_the_staged_file_whole(tmp_path):
    """P0320-G35-SHEDDING: with no direction asked, CCS_IMPORT reads the file itself."""
    case = _file_case(tmp_path)
    script, lines = _built(case)
    assert _ccs_import_file(lines) == str(case.geometry)
    assert not script.pending_input_files
    assert script.entities.labels("boundaries") == {"CCS_FUS": 1}
    assert _index(lines, "CCS_IMPORT") < _index(lines, "SET_SIMULATION_LENGTH_UNITS METER")


def test_p0320_g35_the_row_chooses_the_azimuth_direction_of_every_relaxed_line(tmp_path):
    """P0320-G35-SHEDDING: the run's own copy states the digit; the user's file is untouched."""
    case = _file_case(tmp_path, tail=" / CCS_SHEDDING: AZIMUTH")
    script, lines = _built(case)
    imported = _ccs_import_file(lines)
    assert imported != str(case.geometry)
    assert Path(imported).name == "g35.ccs_shedding.csv"
    copy = script.pending_input_files[imported]
    text = copy.decode("utf-8") if isinstance(copy, bytes) else copy
    assert "Relaxed_TE;0.5;0.2;0.8;1" in text.splitlines()
    original = Path(case.geometry).read_bytes().decode("utf-8")
    assert text.replace("Relaxed_TE;0.5;0.2;0.8;1", "Relaxed_TE;0.5;0.2;0.8") == original
    assert Path(case.geometry).read_text(encoding="utf-8") == RELAXED_FUSELAGE


def test_p0320_g35_the_axial_row_rewrites_a_stated_azimuth_digit(tmp_path):
    """P0320-G35-SHEDDING: 0 (axial) replaces a 1 the file states, in either vocabulary."""
    text = RELAXED_FUSELAGE.replace("Relaxed_TE;0.5;0.2;0.8", "Relaxed_TE;0.5;0.2;0.8;1")
    case = _file_case(tmp_path, text=text, tail=" / CCS_SHEDDING: 0")
    script, lines = _built(case)
    copy = script.pending_input_files[_ccs_import_file(lines)]
    decoded = copy.decode("utf-8") if isinstance(copy, bytes) else copy
    assert "Relaxed_TE;0.5;0.2;0.8;0" in decoded.splitlines()


def test_p0320_g35_the_two_directions_render_two_different_scripts_inputs(tmp_path):
    """P0320-G35-SHEDDING: the control, the two rows differ in the copy and nowhere else."""
    axial = _file_case(tmp_path / "a", tail=" / CCS_SHEDDING: AXIAL")
    azimuth = _file_case(tmp_path / "b", tail=" / CCS_SHEDDING: AZIMUTH")
    first, first_lines = _built(axial)
    second, second_lines = _built(azimuth)
    (a_copy,) = first.pending_input_files.values()
    (b_copy,) = second.pending_input_files.values()
    assert a_copy != b_copy
    assert first_lines == second_lines


@pytest.mark.parametrize(
    ("setup", "needle"),
    [
        ("loft", "kind"),
        ("no-relaxed-line", "Relaxed_TE"),
        ("diagonal", "diagonal"),
    ],
)
def test_p0320_g35_a_direction_nothing_would_apply_is_refused(tmp_path, setup, needle):
    """P0320-G35-SHEDDING: refused on a loft, on a file with no Relaxed_TE, and a third word."""
    if setup == "loft":
        case = _row_case(
            tmp_path,
            "fus",
            'kind = "fuselage"\ncomponent = 2\n',
            ["FUS"],
            tail=" / CCS_SHEDDING: AZIMUTH",
        )
    elif setup == "no-relaxed-line":
        case = _file_case(
            tmp_path, text=ccs_file(_fuselage("CCS_FUS")), tail=" / CCS_SHEDDING: AZIMUTH"
        )
    else:
        case = _file_case(tmp_path, tail=" / CCS_SHEDDING: diagonal")
    with pytest.raises(CampaignConfigError) as refusal:
        _built(case)
    assert needle in str(refusal.value)
    assert "CCS_SHEDDING" in str(refusal.value)


def test_p0320_g35_the_file_route_refuses_boundaries_that_are_not_the_files_components(
    tmp_path,
):
    """P0320-G35-SHEDDING: CCS_IMPORT names each boundary after its component, in order."""
    case = _file_case(tmp_path, boundaries=("SOMETHING",))
    with pytest.raises(CampaignConfigError) as refusal:
        _built(case)
    assert "CCS_FUS" in str(refusal.value) and "SOMETHING" in str(refusal.value)


def test_p0320_g35_the_file_route_refuses_a_stated_unit(tmp_path):
    """P0320-G35-SHEDDING: the file states its own unit, so the table says FILE."""
    case = _row_case(tmp_path, "g35", FILE_ROUTE, ["CCS_FUS"], text=RELAXED_FUSELAGE)
    with pytest.raises(CampaignConfigError, match="FILE"):
        _built(case)


# --- G35: the relaxed trailing-edge specification, settled against SRC-752 p.85 ----------


def test_p0320_g35_the_manuals_line_carries_three_values_before_the_direction():
    """P0320-G35-SHEDDING: ``Relaxed_TE;u;v1;v2;direction`` (SRC-752 p.85), the defect fixed.

    The helper read a four-number text as four leading values with no direction,
    so ``0.5;0.2;0.8;1`` (u, v1, v2 and the azimuth digit) was restated as
    ``0.5;0.2;0.8;1;1``, one value too many.
    """
    edge = helpers.parse_relaxed_trailing_edge("0.5;0.2;0.8;1")
    assert edge.fields == ("0.5", "0.2", "0.8")
    assert edge.direction == "AZIMUTH"
    assert edge.with_shedding("AZIMUTH").render() == "0.5;0.2;0.8;1"
    three = helpers.parse_relaxed_trailing_edge("0.5;0.2;0.8")
    assert three.direction is None and three.render() == "0.5;0.2;0.8"
    assert three.with_shedding(1).render() == "0.5;0.2;0.8;1"


def test_p0320_g35_the_whole_line_keeps_its_keyword():
    """P0320-G35-SHEDDING: the line as a CCS file writes it reads and renders whole."""
    edge = helpers.parse_relaxed_trailing_edge("Relaxed_TE;0.5;0.2;0.8")
    assert edge.fields == ("0.5", "0.2", "0.8") and edge.direction is None
    assert edge.with_shedding("AZIMUTH").render() == "Relaxed_TE;0.5;0.2;0.8;1"
    stated = helpers.parse_relaxed_trailing_edge("Relaxed_TE;0.5;0.2;0.8;0")
    assert stated.direction == "AXIAL" and stated.render() == "Relaxed_TE;0.5;0.2;0.8;0"


@pytest.mark.parametrize("text", ["0.5;0.2", "Relaxed_TE;0.5;0.2", "0.5;0.2;0.8;1;0"])
def test_p0320_g35_a_value_count_the_manual_does_not_print_is_refused(text):
    """P0320-G35-SHEDDING: three values, or four with the direction, and nothing else."""
    with pytest.raises(CommandArgumentError) as refusal:
        helpers.parse_relaxed_trailing_edge(text)
    assert "3" in str(refusal.value) and "4" in str(refusal.value)


def test_p0320_g35_the_sidecar_table_reads_through_the_import_reader(tmp_path):
    """P0320-G35-SHEDDING: ``[import.ccs]`` is read by the reader every import table has."""
    path = tmp_path / "g35.boundaries.toml"
    path.write_text(_sidecar(["CCS_FUS"], FILE_ROUTE, units="FILE"), encoding="utf-8")
    spec = read_mesh_import(path)
    assert spec is not None and spec.units == "FILE"
    assert spec.ccs is not None and spec.ccs.kind == "file"
