"""The CCS body of revolution: a mesh generated by the solver's CCS commands from a row.

Pipeline role: the cases row, where a row's solver commands are emitted.
It emits the CCS body-of-revolution commands of
``commands/ccs_revolve_mesh.yaml`` for a row that asks for one.

Laid down by the 0.32.0 preparation step so work package C3 writes its
code here and touches :mod:`pyflightstream.cases.workflows` only through a
short hook.

The stub's name and signature are a placeholder: the module is what the
contract fixes, and its package may rename the stub when it fills it.
Until then it refuses with
:class:`~pyflightstream._errors.ContractNotImplementedError`.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from pyflightstream._errors import ContractNotImplementedError

if TYPE_CHECKING:
    from pyflightstream.cases import SimCase
    from pyflightstream.script import Script


def emit_ccs_revolution(script: Script, case: SimCase) -> None:
    """Emit the CCS body-of-revolution commands of one point.

    Parameters
    ----------
    script : Script
        The script being built for the point.
    case : SimCase
        The point's case, as the matrix row and its artifacts define it.

    Raises
    ------
    ContractNotImplementedError
        Always, until work package C3 fills this body.
    """
    raise ContractNotImplementedError(
        "pyflightstream.cases.ccs_revolution.emit_ccs_revolution: "
        "not implemented yet (0.32.0 contract)"
    )
