"""The CCS body of revolution: a mesh generated by the solver's CCS commands from a row.

Pipeline role: the cases row, where a row's solver commands are emitted.
It emits the CCS body-of-revolution commands of
``commands/ccs_revolve_mesh.yaml`` and ``commands/cad_create.yaml`` for a
row whose CCS file's ``[import.ccs]`` table says ``kind = "revolution"``:
the curve route's prelude
(:func:`pyflightstream.cases.ccs_wing.emit_curve_prelude`) and the loft
``CAD_CREATE_REVOLVE_MESH_FROM_CCS``, which round 1 accepted on 26.124 with
the saved simulation listing the new boundary (probe C5). The workflows
reach it through :func:`pyflightstream.cases.ccs_wing.emit_ccs_geometry`.

The profile turns about ``axis`` through the origin of the reference frame
(frame 1: the route runs before any frame is created), from
``start_angle_deg`` to ``end_angle_deg``, 0 to 360 by default. What a
negative or a reversed pair of angles does is not stated by the manual and
is not assumed here.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from pyflightstream.cases.ccs_wing import REFERENCE_FRAME, emit_curve_prelude, loft_component
from pyflightstream.script import helpers

if TYPE_CHECKING:
    from pyflightstream.cases import SimCase
    from pyflightstream.script import Script

__all__ = ["emit_ccs_revolution"]


def emit_ccs_revolution(script: Script, case: SimCase) -> None:
    """Emit the CCS body-of-revolution commands of one point.

    Parameters
    ----------
    script : Script
        The script being built for the point.
    case : SimCase
        The point's case, whose ``[import.ccs]`` table says
        ``kind = "revolution"``.

    Raises
    ------
    CampaignConfigError
        As :func:`pyflightstream.cases.ccs_wing.loft_component` refuses: a
        table of another kind among them.
    """
    spec, name, component = loft_component(case, "revolution")
    emit_curve_prelude(script, case, component)
    helpers.assign_selected_ccs_curves(script, "revolution")
    loft_u, loft_v = spec.lofts
    script.emit(
        "CAD_CREATE_REVOLVE_MESH_FROM_CCS",
        name,
        REFERENCE_FRAME,
        spec.axis,
        float(spec.start_angle_deg),
        float(spec.end_angle_deg),
        spec.close_ends,
        loft_u,
        loft_v,
    )
