"""The CCS fuselage: a fuselage mesh generated by the solver's CCS commands from a row.

Pipeline role: the cases row, where a row's solver commands are emitted.
It emits the CCS fuselage commands of ``commands/ccs_fuselage_mesh.yaml``
for a row that asks for a CCS fuselage.

Laid down by the 0.32.0 preparation step so work package C2 writes its
code here and touches :mod:`pyflightstream.cases.workflows` only through a
short hook.

The stub's name and signature are a placeholder: the module is what the
contract fixes, and its package may rename the stub when it fills it.
Until then it refuses with
:class:`~pyflightstream._errors.ContractNotImplementedError`.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from pyflightstream._errors import ContractNotImplementedError

if TYPE_CHECKING:
    from pyflightstream.cases import SimCase
    from pyflightstream.script import Script


def emit_ccs_fuselage(script: Script, case: SimCase) -> None:
    """Emit the CCS fuselage commands of one point.

    Parameters
    ----------
    script : Script
        The script being built for the point.
    case : SimCase
        The point's case, as the matrix row and its artifacts define it.

    Raises
    ------
    ContractNotImplementedError
        Always, until work package C2 fills this body.
    """
    raise ContractNotImplementedError(
        "pyflightstream.cases.ccs_fuselage.emit_ccs_fuselage: not implemented yet (0.32.0 contract)"
    )
