POL  | AIRCRAFT | DESCRIPTION                                                  | FLIGHT_CONDITION       | SWEEP_TYPE | SWEEP_VALUES | REF  | SET  | PPROC | FS_BUILD | HIDDEN | RUN | WORKFLOW       | VAR_NAMES_VALUES
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
3001 | Rotor    | TIME_STUDY_rotor_30_deg_per_step_half_a_revolution           | MACH:0.1441, REmi:4.38 | AL/BE      | 0.0/0.0      | r003 | s002 | p001  | 26.120   |    0   |  1  | unsteady_rotor | GEOMETRY: 30_BLADE.fsm / SYMMETRY: PERIODIC / PERIODIC_COPIES: 6 / ADVANCE_RATIO: 1.7 / RPM_SIGN: 1 / ROTOR_AXIS: X / MOVING_BOUNDARIES: Blade / DELTA_THETA: 30 / REVOLUTIONS: 0.5
3002 | Rotor    | TIME_STUDY_rotor_15_deg_per_step_half_a_revolution           | MACH:0.1441, REmi:4.38 | AL/BE      | 0.0/0.0      | r003 | s002 | p001  | 26.120   |    0   |  1  | unsteady_rotor | GEOMETRY: 30_BLADE.fsm / SYMMETRY: PERIODIC / PERIODIC_COPIES: 6 / ADVANCE_RATIO: 1.7 / RPM_SIGN: 1 / ROTOR_AXIS: X / MOVING_BOUNDARIES: Blade / DELTA_THETA: 15 / REVOLUTIONS: 0.5
3003 | Rotor    | TIME_STUDY_rotor_10_deg_per_step_half_a_revolution           | MACH:0.1441, REmi:4.38 | AL/BE      | 0.0/0.0      | r003 | s002 | p001  | 26.120   |    0   |  1  | unsteady_rotor | GEOMETRY: 30_BLADE.fsm / SYMMETRY: PERIODIC / PERIODIC_COPIES: 6 / ADVANCE_RATIO: 1.7 / RPM_SIGN: 1 / ROTOR_AXIS: X / MOVING_BOUNDARIES: Blade / DELTA_THETA: 10 / REVOLUTIONS: 0.5
3004 | Rotor    | TIME_STUDY_rotor_7p5_deg_per_step_half_a_revolution           | MACH:0.1441, REmi:4.38 | AL/BE      | 0.0/0.0      | r003 | s002 | p001  | 26.120   |    0   |  1  | unsteady_rotor | GEOMETRY: 30_BLADE.fsm / SYMMETRY: PERIODIC / PERIODIC_COPIES: 6 / ADVANCE_RATIO: 1.7 / RPM_SIGN: 1 / ROTOR_AXIS: X / MOVING_BOUNDARIES: Blade / DELTA_THETA: 7.5 / REVOLUTIONS: 0.5
3005 | Rotor    | TIME_STUDY_rotor_5_deg_per_step_half_a_revolution            | MACH:0.1441, REmi:4.38 | AL/BE      | 0.0/0.0      | r003 | s002 | p001  | 26.120   |    0   |  1  | unsteady_rotor | GEOMETRY: 30_BLADE.fsm / SYMMETRY: PERIODIC / PERIODIC_COPIES: 6 / ADVANCE_RATIO: 1.7 / RPM_SIGN: 1 / ROTOR_AXIS: X / MOVING_BOUNDARIES: Blade / DELTA_THETA: 5 / REVOLUTIONS: 0.5
3006 | Rotor    | TIME_STUDY_rotor_2p5_deg_per_step_half_a_revolution           | MACH:0.1441, REmi:4.38 | AL/BE      | 0.0/0.0      | r003 | s002 | p001  | 26.120   |    0   |  1  | unsteady_rotor | GEOMETRY: 30_BLADE.fsm / SYMMETRY: PERIODIC / PERIODIC_COPIES: 6 / ADVANCE_RATIO: 1.7 / RPM_SIGN: 1 / ROTOR_AXIS: X / MOVING_BOUNDARIES: Blade / DELTA_THETA: 2.5 / REVOLUTIONS: 0.5
3010 | Wing     | TIME_STUDY_wing_unsteady_coarse_step_0p02_s_six_steps        | MACH:0.1, REmi:2.3     | AL         | 2.0          | r001 | s002 | p001  | 26.120   |    0   |  1  | unsteady       | GEOMETRY: 10_WING.fsm / SYMMETRY: NONE / DELTA_TIME: 0.02 / TIME_ITERATIONS: 6
3011 | Wing     | TIME_STUDY_wing_unsteady_fine_step_0p01_s_twelve_steps       | MACH:0.1, REmi:2.3     | AL         | 2.0          | r001 | s002 | p001  | 26.120   |    0   |  1  | unsteady       | GEOMETRY: 10_WING.fsm / SYMMETRY: NONE / DELTA_TIME: 0.01 / TIME_ITERATIONS: 12
