POL  | HIDDEN | RUN | AIRCRAFT | CONFIGURATION | DESCRIPTION                                                         | FLIGHT_CONDITION                                                     | SWEEP_VALUES   | GEOMETRY | REF  | SET  | PPROC | SYMMETRY | SYMMETRY_LOADS | NCPUS | WALLTIME | FS_BUILD | WORKFLOW       | VAR_NAMES_VALUES
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
1001 |    0   |  1  | Wing     | -             | STEADY_polar_AL_sweep_MACH_REmi_pins_from_the_setup                 | MACH:0.1, REmi:2.3, ALPHA:sweep | -2.0,0.0,2.0,4.0 | 10_WING.fsm | r001 | s001 | p002  | NONE     | true           | 8     | -        | 26.120   | steady         |
1002 |    0   |  1  | Wing     | -             | STEADY_half_wing_MIRROR_TASmps_and_RHOkgm3_pinned_on_the_row        | TASmps:34.0, RHOkgm3:1.225, ALPHA:sweep | 4.0            | 11_HALFWING.fsm | r001 | s001 | p002  | MIRROR   | true           | 8     | -        | 26.120   | steady         |
1003 |    0   |  1  | Wing     | -             | STEADY_BE_sweep_ALTFT_dISA_atmosphere_no_pins_setup_s004            | MACH:0.1, ALTFT:5000, dISA:10, BETA:sweep | -4.0,0.0,4.0   | 10_WING.fsm | r001 | s004 | p002  | NONE     | true           | 8     | -        | 26.120   | steady         |
1004 |    0   |  1  | Wing     | -             | STEADY_AL_BE_combined_sweep_four_pins_on_the_row_override_setup     | MACH:0.1, REmi:2.3, MUPas:1.8e-5, ASMPS:340.0, TK:290.0, PPA:100000, ALPHA:sweep, BETA:2.0 | 2.0,4.0 | 10_WING.fsm | r001 | s001 | p002  | NONE     | true           | 8     | -        | 26.120   | steady         |
1005 |    1   |  1  | Body     | -             | STEADY_body_BASE_REGIONS_second_build_HIDDEN_window                 | MACH:0.1, REmi:2.3, ALPHA:sweep | 0.0            | 20_BODY.fsm | r002 | s001 | p002  | NONE     | true           | 8     | -        | 26.123   | steady         | BASE_REGIONS: Body
1006 |    1   |  0  | Wing     | -             | STEADY_inactive_row_RUN_0_kept_for_the_record                       | MACH:0.1, REmi:2.3, ALPHA:sweep | 0.0            | 10_WING.fsm | r001 | s001 | p002  | NONE     | true           | 8     | -        | 26.120   | steady         |
1010 |    0   |  1  | Wing     | -             | UNSTEADY_rotorless_DELTA_TIME_TIME_ITERATIONS_WINDOW_STEPS          | MACH:0.1, REmi:2.3, ALPHA:sweep | 2.0            | 10_WING.fsm | r001 | s002 | p001  | NONE     | false          | 8     | -        | 26.120   | unsteady       | DELTA_TIME: 0.01 / TIME_ITERATIONS: 12 / WINDOW_STEPS: 6
1011 |    0   |  1  | Wing     | -             | UNSTEADY_rotorless_azimuthal_clock_ADVANCE_RATIO_WINDOW_REVOLUTIONS | MACH:0.1, REmi:2.3, ALPHA:sweep | 2.0            | 10_WING.fsm | r001 | s002 | p001  | NONE     | false          | 8     | -        | 26.120   | unsteady       | DELTA_THETA: 30 / REVOLUTIONS: 0.5 / ADVANCE_RATIO: 1.3 / WINDOW_REVOLUTIONS: 0.25
1020 |    0   |  1  | Rotor    | -             | UNSTEADY_ROTOR_one_blade_PERIODIC_six_copies_azimuthal_clock        | MACH:0.1441, REmi:4.38, ALPHA:sweep, BETA:0.0 | 0.0 | 30_BLADE.fsm | r003 | s002 | p001  | PERIODIC | false          | 8     | -        | 26.120   | unsteady_rotor | PERIODIC_COPIES: 6 / ROTOR_SHEDDING: AZIMUTH / DELTA_THETA: 30 / REVOLUTIONS: 0.5 / WINDOW_DEGREES: 60 / CLOCK_MOTION: ROTOR / MOTIONS: {MOVING_BC_ALIAS: ROTOR / ADVANCE_RATIO: 1.7}
1021 |    0   |  1  | Pusher   | -             | UNSTEADY_ROTOR_installed_behind_a_body_signed_RPM_ROTOR_ORIGIN_point | MACH:0.1, REmi:2.3, ALPHA:sweep | 0.0            | 40_PUSHER.fsm | r004 | s002 | p003  | NONE     | false          | 8     | -        | 26.120   | unsteady_rotor | BASE_REGIONS: Body / DELTA_THETA: 30 / REVOLUTIONS: 0.5 / CLOCK_MOTION: PUSHER / MOTIONS: {MOVING_BC_ALIAS: PUSHER / RPM: 800} / LAST_REVS_AVG: 1
1022 |    0   |  1  | Twin     | -             | UNSTEADY_ROTOR_two_rotors_MOTIONS_list_origins_by_reference_point   | MACH:0.1, REmi:2.3, ALPHA:sweep | 0.0            | 41_TWIN.fsm | r006 | s002 | p005  | NONE     | false          | 8     | -        | 26.120   | unsteady_rotor | DELTA_THETA: 30 / REVOLUTIONS: 0.5 / CLOCK_MOTION: PORT / MOTIONS: {MOVING_BC_ALIAS: PORT / RPM: 800}, {MOVING_BC_ALIAS: STARBOARD / RPM: 800} / LAST_REVS_AVG: 1
1090 |    0   |  1  | Wing     | -             | LEGACY_recipe_named_in_the_cell_OUTPUTS_and_LOG_OUTPUT_keys         | MACH:0.1, REmi:2.3, ALPHA:sweep | 0.0,2.0        | 10_WING.fsm | r001 | s001 | p002  | -        | true           | 8     | -        | 26.120   | LEGACY         | RECIPE: tests.tier3_licensed.recipes:steady_with_a_log / OUTPUTS: loads_{point}.txt / LOG_OUTPUT: log_{point}.txt
