POL  | HIDDEN | RUN | AIRCRAFT | CONFIGURATION | DESCRIPTION                                                        | FLIGHT_CONDITION                        | SWEEP_VALUES | GEOMETRY        | REF  | SET  | PPROC | SYMMETRY | SYMMETRY_LOADS | NCPUS | WALLTIME | FS_BUILD | WORKFLOW | VAR_NAMES_VALUES
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
5007 |    0   |  1  | Wing     | -             | VOLUME_SECTION_behind_the_AR8_wing_two_points_of_one_sweep         | TASmps:30.0, RHOkgm3:1.225, ALPHA:sweep | 0.0,4.0      | 12_WING_PHY.fsm | r005 | s010 | p007  | NONE     | -              | -     | -        | 26.124   | steady   |
5008 |    0   |  1  | Wing     | -             | ACTUATOR_disc_ahead_of_the_wing_loaded_by_its_net_thrust           | TASmps:30.0, RHOkgm3:1.225, ALPHA:sweep | 4.0          | 12_WING_PHY.fsm | r008 | s010 | p002  | NONE     | -              | -     | -        | 26.124   | steady   | ACTUATOR: PROP / ACTUATOR_RPM: 2400 / ACTUATOR_THRUST: 120
5009 |    0   |  1  | Wing     | -             | ACTUATOR_disc_ahead_of_the_wing_loaded_by_a_radial_profile_file    | TASmps:30.0, RHOkgm3:1.225, ALPHA:sweep | 4.0          | 12_WING_PHY.fsm | r008 | s010 | p002  | NONE     | -              | -     | -        | 26.124   | steady   | ACTUATOR: PROP / ACTUATOR_RPM: 2400 / PROFILE: prop_ct
5010 |    0   |  1  | Wing     | -             | ACTUATOR_control_the_same_reference_and_no_disc                    | TASmps:30.0, RHOkgm3:1.225, ALPHA:sweep | 4.0          | 12_WING_PHY.fsm | r008 | s010 | p002  | NONE     | -              | -     | -        | 26.124   | steady   |
5012 |    0   |  1  | Wing     | -             | CUSTOM_FREESTREAM_the_same_uniform_field_at_0_deg_against_5013     | TASmps:30.0, RHOkgm3:1.225, ALPHA:sweep | 0.0          | 12_WING_PHY.fsm | r008 | s010 | p002  | NONE     | -              | -     | -        | 26.124   | steady   | FREESTREAM: fs_uniform
5013 |    0   |  1  | Wing     | -             | CUSTOM_FREESTREAM_control_the_constant_free_stream_at_0_deg        | TASmps:30.0, RHOkgm3:1.225, ALPHA:sweep | 0.0          | 12_WING_PHY.fsm | r008 | s010 | p002  | NONE     | -              | -     | -        | 26.124   | steady   |
5014 |    0   |  1  | Wing     | -             | CUSTOM_FREESTREAM_sheared_in_z_about_the_rows_speed_at_0_deg       | TASmps:30.0, RHOkgm3:1.225, ALPHA:sweep | 0.0          | 12_WING_PHY.fsm | r008 | s010 | p002  | NONE     | -              | -     | -        | 26.124   | steady   | FREESTREAM: fs_shear
