POL  | HIDDEN | RUN | AIRCRAFT | CONFIGURATION | DESCRIPTION                                                        | FLIGHT_CONDITION                              | SWEEP_VALUES | GEOMETRY             | REF  | SET  | PPROC | SYMMETRY | SYMMETRY_LOADS | NCPUS | WALLTIME | FS_BUILD | WORKFLOW | VAR_NAMES_VALUES
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
4101 |    0   |  1  | Wing     | -             | MESH_wing_the_saved_simulation_the_control_of_both_OBJ_routes      | MACH:0.1, REmi:2.3, ALPHA:sweep               | 4.0          | 10_WING.fsm          | r001 | s009 | p008  | NONE     | true           | 8     | -        | 26.124   | steady   | ADDITIONAL_PPROC: p009
4102 |    0   |  1  | Wing     | -             | MESH_wing_OBJ_its_trailing_edge_by_the_points_file                 | MACH:0.1, REmi:2.3, ALPHA:sweep               | 4.0          | 15_WING_OBJ_TE.obj   | r001 | s009 | p008  | NONE     | true           | 8     | -        | 26.124   | steady   | ADDITIONAL_PPROC: p009
4103 |    0   |  1  | Wing     | -             | MESH_wing_OBJ_its_trailing_edge_detected                           | MACH:0.1, REmi:2.3, ALPHA:sweep               | 4.0          | 16_WING_OBJ_DET.obj  | r001 | s009 | p008  | NONE     | true           | 8     | -        | 26.124   | steady   |
4104 |    0   |  1  | Wing     | -             | MESH_wing_OBJ_written_in_MILLIMETER_does_IMPORT_convert_it         | MACH:0.1, REmi:2.3, ALPHA:sweep               | 4.0          | 17_WING_OBJ_MM.obj   | r001 | s009 | p008  | NONE     | true           | 8     | -        | 26.124   | steady   |
4105 |    0   |  1  | Wing     | -             | MESH_wing_the_saved_simulation_unsteady_for_the_additional_post    | MACH:0.1, REmi:2.3, ALPHA:sweep               | 2.0          | 10_WING.fsm          | r001 | s011 | p001  | NONE     | false          | 8     | -        | 26.124   | unsteady | DELTA_TIME: 0.01 / TIME_ITERATIONS: 12 / LAST_ITERS_AVG: 6 / ADDITIONAL_PPROC: p009
4111 |    0   |  1  | Blade    | -             | MESH_blade_the_saved_simulation_the_control_of_both_OBJ_routes     | MACH:0.1441, REmi:4.38, ALPHA:sweep, BETA:0.0 | 0.0          | 30_BLADE.fsm         | r003 | s009 | p008  | NONE     | true           | 8     | -        | 26.124   | steady   |
4112 |    0   |  1  | Blade    | -             | MESH_blade_OBJ_its_trailing_edge_by_the_points_file                | MACH:0.1441, REmi:4.38, ALPHA:sweep, BETA:0.0 | 0.0          | 32_BLADE_OBJ_TE.obj  | r003 | s009 | p008  | NONE     | true           | 8     | -        | 26.124   | steady   |
4113 |    0   |  1  | Blade    | -             | MESH_blade_OBJ_its_trailing_edge_detected                          | MACH:0.1441, REmi:4.38, ALPHA:sweep, BETA:0.0 | 0.0          | 33_BLADE_OBJ_DET.obj | r003 | s009 | p008  | NONE     | true           | 8     | -        | 26.124   | steady   |
