POL  | HIDDEN | RUN | AIRCRAFT | CONFIGURATION | DESCRIPTION                                                  | FLIGHT_CONDITION       | SWEEP_VALUES | GEOMETRY | REF  | SET  | PPROC | SYMMETRY | SYMMETRY_LOADS | NCPUS | WALLTIME | FS_BUILD | WORKFLOW       | VAR_NAMES_VALUES
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
3001 |    0   |  1  | Rotor    | -             | TIME_STUDY_rotor_30_deg_per_step_half_a_revolution           | MACH:0.1441, REmi:4.38, ALPHA:sweep, BETA:0.0 | 0.0 | 30_BLADE.fsm | r003 | s002 | p001  | PERIODIC | false          | 8     | -        | 26.120   | unsteady_rotor | PERIODIC_COPIES: 6 / ADVANCE_RATIO: 1.7 / RPM_SIGN: 1 / ROTOR_AXIS: X / MOVING_BOUNDARIES: Blade / DELTA_THETA: 30 / REVOLUTIONS: 0.5
3002 |    0   |  1  | Rotor    | -             | TIME_STUDY_rotor_15_deg_per_step_half_a_revolution           | MACH:0.1441, REmi:4.38, ALPHA:sweep, BETA:0.0 | 0.0 | 30_BLADE.fsm | r003 | s002 | p001  | PERIODIC | false          | 8     | -        | 26.120   | unsteady_rotor | PERIODIC_COPIES: 6 / ADVANCE_RATIO: 1.7 / RPM_SIGN: 1 / ROTOR_AXIS: X / MOVING_BOUNDARIES: Blade / DELTA_THETA: 15 / REVOLUTIONS: 0.5
3003 |    0   |  1  | Rotor    | -             | TIME_STUDY_rotor_10_deg_per_step_half_a_revolution           | MACH:0.1441, REmi:4.38, ALPHA:sweep, BETA:0.0 | 0.0 | 30_BLADE.fsm | r003 | s002 | p001  | PERIODIC | false          | 8     | -        | 26.120   | unsteady_rotor | PERIODIC_COPIES: 6 / ADVANCE_RATIO: 1.7 / RPM_SIGN: 1 / ROTOR_AXIS: X / MOVING_BOUNDARIES: Blade / DELTA_THETA: 10 / REVOLUTIONS: 0.5
3004 |    0   |  1  | Rotor    | -             | TIME_STUDY_rotor_7p5_deg_per_step_half_a_revolution           | MACH:0.1441, REmi:4.38, ALPHA:sweep, BETA:0.0 | 0.0 | 30_BLADE.fsm | r003 | s002 | p001  | PERIODIC | false          | 8     | -        | 26.120   | unsteady_rotor | PERIODIC_COPIES: 6 / ADVANCE_RATIO: 1.7 / RPM_SIGN: 1 / ROTOR_AXIS: X / MOVING_BOUNDARIES: Blade / DELTA_THETA: 7.5 / REVOLUTIONS: 0.5
3005 |    0   |  1  | Rotor    | -             | TIME_STUDY_rotor_5_deg_per_step_half_a_revolution            | MACH:0.1441, REmi:4.38, ALPHA:sweep, BETA:0.0 | 0.0 | 30_BLADE.fsm | r003 | s002 | p001  | PERIODIC | false          | 8     | -        | 26.120   | unsteady_rotor | PERIODIC_COPIES: 6 / ADVANCE_RATIO: 1.7 / RPM_SIGN: 1 / ROTOR_AXIS: X / MOVING_BOUNDARIES: Blade / DELTA_THETA: 5 / REVOLUTIONS: 0.5
3006 |    0   |  1  | Rotor    | -             | TIME_STUDY_rotor_2p5_deg_per_step_half_a_revolution           | MACH:0.1441, REmi:4.38, ALPHA:sweep, BETA:0.0 | 0.0 | 30_BLADE.fsm | r003 | s002 | p001  | PERIODIC | false          | 8     | -        | 26.120   | unsteady_rotor | PERIODIC_COPIES: 6 / ADVANCE_RATIO: 1.7 / RPM_SIGN: 1 / ROTOR_AXIS: X / MOVING_BOUNDARIES: Blade / DELTA_THETA: 2.5 / REVOLUTIONS: 0.5
3010 |    0   |  1  | Wing     | -             | TIME_STUDY_wing_unsteady_coarse_step_0p02_s_six_steps        | MACH:0.1, REmi:2.3, ALPHA:sweep | 2.0          | 10_WING.fsm | r001 | s002 | p001  | NONE     | false          | 8     | -        | 26.120   | unsteady       | DELTA_TIME: 0.02 / TIME_ITERATIONS: 6
3011 |    0   |  1  | Wing     | -             | TIME_STUDY_wing_unsteady_fine_step_0p01_s_twelve_steps       | MACH:0.1, REmi:2.3, ALPHA:sweep | 2.0          | 10_WING.fsm | r001 | s002 | p001  | NONE     | false          | 8     | -        | 26.120   | unsteady       | DELTA_TIME: 0.01 / TIME_ITERATIONS: 12
