POL  | AIRCRAFT | DESCRIPTION                                                         | FLIGHT_CONDITION                                                     | SWEEP_VALUES   | REF  | SET  | PPROC | FS_BUILD | HIDDEN | RUN | WORKFLOW       | VAR_NAMES_VALUES
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
1001 | Wing     | STEADY_polar_AL_sweep_MACH_REmi_pins_from_the_setup                 | MACH:0.1, REmi:2.3, ALPHA:sweep | -2.0,0.0,2.0,4.0 | r001 | s001 | p002  | 26.120   |    0   |  1  | steady         | GEOMETRY: 10_WING.fsm / SYMMETRY: NONE
1002 | Wing     | STEADY_half_wing_MIRROR_TASmps_and_RHOkgm3_pinned_on_the_row        | TASmps:34.0, RHOkgm3:1.225, ALPHA:sweep | 4.0            | r001 | s001 | p002  | 26.120   |    0   |  1  | steady         | GEOMETRY: 11_HALFWING.fsm / SYMMETRY: MIRROR
1003 | Wing     | STEADY_BE_sweep_ALTFT_dISA_atmosphere_no_pins_setup_s004            | MACH:0.1, ALTFT:5000, dISA:10, BETA:sweep | -4.0,0.0,4.0   | r001 | s004 | p002  | 26.120   |    0   |  1  | steady         | GEOMETRY: 10_WING.fsm / SYMMETRY: NONE
1004 | Wing     | STEADY_AL_BE_combined_sweep_four_pins_on_the_row_override_setup     | MACH:0.1, REmi:2.3, MUPas:1.8e-5, ASMPS:340.0, TK:290.0, PPA:100000, ALPHA:sweep, BETA:2.0 | 2.0,4.0 | r001 | s001 | p002  | 26.120   |    0   |  1  | steady         | GEOMETRY: 10_WING.fsm / SYMMETRY: NONE
1005 | Body     | STEADY_body_BASE_REGIONS_second_build_HIDDEN_window                 | MACH:0.1, REmi:2.3, ALPHA:sweep | 0.0            | r002 | s001 | p002  | 26.123   |    1   |  1  | steady         | GEOMETRY: 20_BODY.fsm / SYMMETRY: NONE / BASE_REGIONS: Body
1006 | Wing     | STEADY_inactive_row_RUN_0_kept_for_the_record                       | MACH:0.1, REmi:2.3, ALPHA:sweep | 0.0            | r001 | s001 | p002  | 26.120   |    1   |  0  | steady         | GEOMETRY: 10_WING.fsm / SYMMETRY: NONE
1010 | Wing     | UNSTEADY_rotorless_DELTA_TIME_TIME_ITERATIONS_WINDOW_STEPS          | MACH:0.1, REmi:2.3, ALPHA:sweep | 2.0            | r001 | s002 | p001  | 26.120   |    0   |  1  | unsteady       | GEOMETRY: 10_WING.fsm / SYMMETRY: NONE / DELTA_TIME: 0.01 / TIME_ITERATIONS: 12 / WINDOW_STEPS: 6
1011 | Wing     | UNSTEADY_rotorless_azimuthal_clock_ADVANCE_RATIO_WINDOW_REVOLUTIONS | MACH:0.1, REmi:2.3, ALPHA:sweep | 2.0            | r001 | s002 | p001  | 26.120   |    0   |  1  | unsteady       | GEOMETRY: 10_WING.fsm / SYMMETRY: NONE / DELTA_THETA: 30 / REVOLUTIONS: 0.5 / ADVANCE_RATIO: 1.3 / WINDOW_REVOLUTIONS: 0.25
1020 | Rotor    | UNSTEADY_ROTOR_one_blade_PERIODIC_six_copies_azimuthal_clock        | MACH:0.1441, REmi:4.38, ALPHA:sweep, BETA:0.0 | 0.0 | r003 | s002 | p001  | 26.120   |    0   |  1  | unsteady_rotor | GEOMETRY: 30_BLADE.fsm / SYMMETRY: PERIODIC / PERIODIC_COPIES: 6 / ADVANCE_RATIO: 1.7 / RPM_SIGN: 1 / ROTOR_AXIS: X / MOVING_BOUNDARIES: Blade / BLADES: 6 / ROTOR_SHEDDING: AZIMUTH / DELTA_THETA: 30 / REVOLUTIONS: 0.5 / WINDOW_DEGREES: 60
1021 | Pusher   | UNSTEADY_ROTOR_installed_behind_a_body_signed_RPM_ROTOR_ORIGIN_point | MACH:0.1, REmi:2.3, ALPHA:sweep | 0.0            | r004 | s002 | p001  | 26.120   |    0   |  1  | unsteady_rotor | GEOMETRY: 40_PUSHER.fsm / SYMMETRY: NONE / RPM: -800 / ROTOR_AXIS: X / ROTOR_ORIGIN: ERP3 / MOVING_BOUNDARIES: Blade / BASE_REGIONS: Body / DELTA_THETA: 30 / REVOLUTIONS: 0.5
1022 | Twin     | UNSTEADY_ROTOR_two_rotors_MOTIONS_list_origins_by_reference_point   | MACH:0.1, REmi:2.3, ALPHA:sweep | 0.0            | r004 | s002 | p003  | 26.120   |    0   |  1  | unsteady_rotor | GEOMETRY: 41_TWIN.fsm / SYMMETRY: NONE / DELTA_THETA: 30 / REVOLUTIONS: 0.5 / CLOCK_MOTION: Blade1 / MOTIONS: {MOVING_BOUNDARIES: Blade1 / RPM: 800 / ROTOR_AXIS: X / ROTOR_ORIGIN: ERP1}, {MOVING_BOUNDARIES: Blade2 / RPM: -800 / ROTOR_AXIS: X / ROTOR_ORIGIN: ERP2}
1090 | Wing     | LEGACY_recipe_named_in_the_cell_OUTPUTS_and_LOG_OUTPUT_keys         | MACH:0.1, REmi:2.3, ALPHA:sweep | 0.0,2.0        | r001 | s001 | p002  | 26.120   |    0   |  1  | LEGACY         | RECIPE: tests.tier3_licensed.recipes:steady_with_a_log / GEOMETRY: 10_WING.fsm / OUTPUTS: loads_{point}.txt / LOG_OUTPUT: log_{point}.txt
