#!/usr/bin/env python3
"""Write the living physics report: each case across the builds, as they arrive.

    python scripts/build_living_physics.py            # write the report
    python scripts/build_living_physics.py --check    # fail if it is stale

PFS-2018.06, and it is GENERATED rather than written, which is the whole of
what "living" means here. A hand-maintained comparison is a document somebody
has to remember to update when a build arrives, and this repository already
carries the measurement of what happens then: a fact restated in five places
drifted to four different numbers, and two pages said six where seven existed.

IT BEGINS AT 26.123 AND GROWS FORWARD, on the owner's decision of 2026-09-13,
and it does NOT back-fill. The four per-build physics reports and the two
drift reports already committed stay as the historical record and are not
folded in. Back-filling would mean re-deriving a verdict for every build ever
registered, and the older evidence already says what it says.

WHAT IT COMPARES: one row per case, one column per build at or after the
floor, carrying that case's verdict tally on that build. A case whose tally
moves between two builds is the thing the report exists to make visible
without anyone diffing two documents by hand.

WHAT IT DOES NOT DO, said here rather than discovered: it does not judge. The
verdicts are the ones the per-build reports already recorded, and this reads
them. A case that never ran on a build is EMPTY and says so; empty is not a
pass.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parents[1]
PHYSICS = REPO / "reports" / "physics"
REPORT = PHYSICS / "LIVING-PHYSICS-ACROSS-BUILDS.md"

#: Her decision of 2026-09-13: the report BEGINS here. A build older than this
#: keeps its own per-build report and is not folded in.
OLDEST_BUILD = "26.123"

#: One per-build physics report, named for the build it measured.
PHY_FILE = re.compile(r"^PHY-(\d{5})_.*\.yaml$")


def canonical(build: str) -> str:
    """Turn the five digits of a file name into the canonical build id."""
    return f"{build[:2]}.{build[2:]}"


def builds_at_or_after(floor: str) -> dict[str, Path]:
    """Every per-build physics report the floor admits, newest last.

    A build with SEVERAL reports keeps the last by file name, which is the
    latest run of it: the name carries the date.
    """
    found: dict[str, Path] = {}
    for path in sorted(PHYSICS.glob("PHY-*.yaml")):
        match = PHY_FILE.match(path.name)
        if not match:
            continue
        build = canonical(match.group(1))
        if build < floor:
            continue
        found[build] = path
    return dict(sorted(found.items()))


def tally(case: dict) -> dict[str, int]:
    """Count the verdicts of one case, by their own words."""
    verdicts = case.get("verdicts") or {}
    counts: dict[str, int] = {}
    for value in verdicts.values():
        counts[str(value)] = counts.get(str(value), 0) + 1
    return counts


def spell(counts: dict[str, int]) -> str:
    """One cell: the tally, or the word that says the case did not run."""
    if not counts:
        return "not run"
    order = ("pass", "warn", "fail", "no_reference")
    parts = [f"{counts[k]} {k}" for k in order if k in counts]
    parts += [f"{v} {k}" for k, v in sorted(counts.items()) if k not in order]
    return ", ".join(parts)


def build_report() -> str:
    """Render the whole report from the per-build evidence on disk."""
    reports = builds_at_or_after(OLDEST_BUILD)
    per_build: dict[str, dict] = {}
    for build, path in reports.items():
        per_build[build] = yaml.safe_load(path.read_text(encoding="utf-8")) or {}

    cases: list[str] = []
    for data in per_build.values():
        for name in data.get("cases") or {}:
            if name not in cases:
                cases.append(name)
    cases.sort()

    lines: list[str] = []
    lines.append("<!-- GENERATED by scripts/build_living_physics.py. Do not edit by hand. -->")
    lines.append(f"<!-- oldest_build: {OLDEST_BUILD} -->")
    lines.append("")
    lines.append("# Each physics case, across the builds, as they arrive")
    lines.append("")
    lines.append(
        "PFS-2018.06. This page is GENERATED from the per-build physics reports in this "
        "folder; the generator is `scripts/build_living_physics.py` and a tier-1 test "
        "refuses a stale copy of this file, so a build that arrives shows up here without "
        "anyone remembering to add it."
    )
    lines.append("")
    lines.append(
        f"**It begins at {OLDEST_BUILD} and grows forward, and it does not back-fill.** That is "
        "the owner's decision of 2026-09-13. The earlier per-build reports and the drift "
        "reports beside them stay as the historical record and are not folded in: they "
        "already say what they say, and re-deriving a verdict for every build ever "
        "registered is work the decision exists to avoid."
    )
    lines.append("")
    lines.append(
        "**It does not judge.** Every verdict below is the one the per-build report already "
        "recorded. A case that never ran on a build reads `not run`, which is not a pass."
    )
    lines.append("")

    if not reports:
        lines.append(
            f"No per-build physics report at or after {OLDEST_BUILD} is committed yet, so this "
            "page has nothing to compare. It is not empty because a case failed; it is empty "
            "because the evidence it reads does not exist yet."
        )
        return "\n".join(lines) + "\n"

    header = "| case | title | " + " | ".join(reports) + " |"
    rule = "|---|---|" + "---|" * len(reports)
    lines.append(header)
    lines.append(rule)
    for name in cases:
        title = ""
        cells = []
        for build in reports:
            case = (per_build[build].get("cases") or {}).get(name)
            if case is None:
                cells.append("not run")
                continue
            title = title or str(case.get("title") or "")
            cells.append(spell(tally(case)))
        lines.append(f"| `{name}` | {title} | " + " | ".join(cells) + " |")

    lines.append("")
    lines.append("## What each build's report said in total")
    lines.append("")
    lines.append("| build | pass | warn | fail | no reference | measured |")
    lines.append("|---|---|---|---|---|---|")
    for build, data in per_build.items():
        summary = data.get("summary") or {}
        lines.append(
            f"| {build} | {summary.get('pass', 0)} | {summary.get('warn', 0)} | "
            f"{summary.get('fail', 0)} | {summary.get('no_reference', 0)} | "
            f"{data.get('date', 'unstated')} |"
        )
    lines.append("")
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    """Write the report, or with --check refuse a stale one."""
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="do not write; exit 1 if the committed report is not what this would write",
    )
    args = parser.parse_args(argv)

    rendered = build_report()
    if args.check:
        if not REPORT.is_file():
            print(f"{REPORT} does not exist; run this without --check")
            return 1
        current = REPORT.read_text(encoding="utf-8")
        if current != rendered:
            print(
                f"{REPORT.name} is STALE: the evidence on disk would render a different page. "
                "Run scripts/build_living_physics.py. This is the check that makes the page "
                "living rather than a document somebody has to remember."
            )
            return 1
        print(f"{REPORT.name} is current")
        return 0
    REPORT.write_text(rendered, encoding="utf-8")
    print(f"wrote {REPORT.relative_to(REPO).as_posix()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
