"""Write the sorted list of commands a registered build cannot emit.

    python scripts/gen_absent_commands.py 26.123

A build registered with ``inherits_base: false`` starts with no evidence
at all, so every command answers absent until a row is written for it.
That gap is the honest state of a brand-new build and it is also
invisible: nothing fails, the emitter simply refuses, one command at a
time, wherever a caller happens to reach one.

So the gap is committed as a NUMBER AND A LIST rather than left as an
impression. The list is generated from the database by this script and
compared by a tier-1 test, so it cannot drift from what the emitter
actually does, and a reader can see what the build owes by opening one
file instead of running a query.

It is deliberately general rather than written for one build: the same
question arrives with every build the author decides should inherit
nothing, and a script named for 26.123 would be copied rather than
reused.

THE COMPARISON IS OVER THE WHOLE FILE, HEADER INCLUDED, and that is a
choice rather than an oversight. The header carries the two counts, and a
count that no test reads is a count that goes stale; comparing it means a
row written for the build moves both the list and the numbers describing
it in one edit. The cost is that the file is regenerated whenever the
database gains or loses an entry even if this build's absent set is
unchanged, and the guard's message says so rather than blaming the list.
An earlier version of this docstring claimed the header was ignored,
which was never true of the test it feeds.
"""

from __future__ import annotations

import argparse
from pathlib import Path

from pyflightstream.commands import CommandRegistry
from pyflightstream.versions import (
    AmbiguousVersionAliasError,
    UnknownVersionError,
    resolve,
)

REPO_ROOT = Path(__file__).resolve().parents[1]
GOLDENS = REPO_ROOT / "tests" / "goldens"


def absent_commands(canonical: str) -> list[str]:
    """Return every command name that answers absent on one build.

    Parameters
    ----------
    canonical : str
        Canonical build identifier, for example ``"26.123"``. Resolved
        through :func:`pyflightstream.versions.resolve`, so an
        unregistered or mistyped identifier is refused with the message
        that names every registered build rather than with a bare key
        error.

    Returns
    -------
    list of str
        Command names, sorted, for which ``evidence_in`` returns None on
        that build. Emptiness is a legitimate answer and means the build
        answers for every command in the database.

    Raises
    ------
    pyflightstream.versions.UnknownVersionError
        If the identifier names no registered build.
    pyflightstream.versions.AmbiguousVersionAliasError
        If it is a vendor name shared by more than one build.
    """
    target = resolve(canonical)
    registry = CommandRegistry.load()
    return sorted(
        name for name, entry in registry.commands.items() if entry.evidence_in(target) is None
    )


def render(canonical: str) -> str:
    """Render the committed file body for one build, LF, with its header."""
    target = resolve(canonical)
    registry = CommandRegistry.load()
    absent = absent_commands(target.canonical)
    header = [
        f"# Commands that answer ABSENT on {target.canonical}, so the emitter refuses them.",
        f"# entries in the database: {len(registry.commands)}",
        f"# absent on this build:    {len(absent)}",
        "# Generated by scripts/gen_absent_commands.py; do not hand-edit.",
    ]
    return "\n".join(header + absent) + "\n"


def golden_path(canonical: str) -> Path:
    """Return the committed location of one build's enumeration.

    The identifier is RESOLVED before it reaches the file name, so the
    stem cannot be steered by the argument: ``26.123`` and ``26123``
    would otherwise collapse onto one file, and an argument carrying a
    separator would write outside the goldens directory entirely.
    """
    target = resolve(canonical)
    return GOLDENS / f"absent_on_{target.canonical.replace('.', '')}.txt"


def main() -> None:
    """Write one build's enumeration into the goldens directory."""
    parser = argparse.ArgumentParser(
        description=__doc__,
        # RAW, because the default formatter collapses all whitespace and
        # re-wraps, so this module's usage line lands mid-paragraph as
        # running prose. `pyfs-manual` uses the raw formatter at every
        # subparser for exactly this reason.
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "canonical",
        metavar="CANONICAL",
        help="registered canonical build identifier, for example 26.123",
    )
    args = parser.parse_args()
    # THE LIBRARY'S OWN MESSAGE, DELIVERED AS A REFUSAL. This module's
    # docstring promises that a mistyped identifier is refused with the
    # message naming every registered build, and the message is indeed
    # good; `main` just never let anyone read it as a refusal, because
    # both version errors propagated and the user saw a stack trace with
    # the sentence buried in it. `pyfs-qa` solved this once already and
    # wrote down why: letting them propagate shows a traceback where the
    # library's own message already says what to do. An ambiguous alias
    # is the likelier of the two here, since the vendor name a solver
    # PRINTS is shared by several builds.
    try:
        path = golden_path(args.canonical)
        body = render(args.canonical)
    except (UnknownVersionError, AmbiguousVersionAliasError) as error:
        raise SystemExit(str(error)) from None
    path.write_bytes(body.encode("utf-8"))
    print(f"wrote {path.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
